# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856dfe69a5f48683357c44759c6eb5903b79aa47d65c7c4b933cdb9977c574128db723152403ace4c7ff3d106800beede93d6888fed4c76983341167ffafb703

test:
  secret_key_base: 2c0947223c947f88f38d090f81bf60c9474bc13d8f6adc8f2e1078505f89b3dac7f73f7da29795fbdb51ea6d5d33d75774098522a5ce9c7fca7189e4b9b34762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
